### ISSUE TITLE
Idea: Expose current stable version

### ISSUE THREAD

**Issue by mdp** [robocorp/rcc#10]
It's not immediately clear what the stable version of RCC is via Github. I periodically check to see if there's an update and sometimes check on the Changelog but it's not clear where stable is.

Updating the README with the current stable version would allow me to quickly know whether or not I need to upgrade.

Another option would be a check on launch to see if a newer version is available. Or even an update option, but that's a bit more involved.

And another option is to embrace the GitHub releases to distribute the binary and expose what the latest stable version is. I've had good luck with Goreleaser for my go projects distributions - https://github.com/mdp/qrterminal

Anyways, this is of course a very low priority issue, but just thought I'd toss in my 2 cents on a bike shed problem :)

**Comment by vjmp** [comment]
Thank you for idea.

I added link in download table to [latest version information text file](https://downloads.robocorp.com/rcc/releases/latest/version.txt). That is version you get from direct downloads. And in Mac OS and Windows cases, those are signed binaries, that are build outside this open source repo of rcc. So that is actually latest _signed_ and _published_ version (manual control). This is what our Lab, Code, and App will start to use.

I know this is **NOT** what you are asking for, and currently we don't have any long term support (LTS) in place **yet**. Currently there are no resources to keep multiple major versions up.

Current rcc development model is [semver aware](https://semver.org/), trunk based, and roll forward. 

**Trunk based** means, that master branch is considered to be "good enough" is pipeline passes. And if additionally our secondary signing pipeline passes. 

And **roll forward** means that if master branch sometimes fails (and it will), or there some critical bug, goal is to fix it ASAP. So that pipelines are back to green, and master will be better than previous versions.

And if you find bugs, or missing features, please let us know. Just submit issue here on Github.

Is this enough for now?

**Comment by kariharju** [comment]
Yeah good ping on this @mdp.

I think the link to the version number is a good solution for now.

The latest signed (mac notarized) executables signals the version of RCC that has been tested under either Robocorp Lab, App or Code. This is the version that is available over brew for Mac users and we are looking to add Chocolatey support as well.

**Comment by mdp** [comment]
Yeah this makes sense and the version link solves my issues. Thanks!
