### ISSUE TITLE
 Recommended way to run parallel robots via RCC (locally)

### ISSUE THREAD

**Issue by sebastianhaberey** [robocorp/rcc#21]
Hi all,

I am trying to run ten robots at the same time via RCC. I am calling my tasks asynchronously via

```
rcc run --task "Robot" --space space-0
```
(space-1, space-2 etc). This works _sometimes_ but at other times I get:
```
panic: mkdir C:\Users\xxx\AppData\Local\robocorp\holotree\h2edd75df4aa9472ct: Access is denied. [recovered]
	panic: mkdir C:\Users\xxx\AppData\Local\robocorp\holotree\h2edd75df4aa9472ct: Access is denied. [recovered]
	panic: mkdir C:\Users\xxx\AppData\Local\robocorp\holotree\h2edd75df4aa9472ct: Access is denied. [recovered]
	panic: mkdir C:\Users\xxx\AppData\Local\robocorp\holotree\h2edd75df4aa9472ct: Access is denied.
```
I am guessing the instances try to access this directory simultaneously and a conflict arises. But why? Am I using RCC wrong? I'd appreciate any pointers into the right direction!

Edit: BTW we are using RCC v9.16.0

**Comment by kariharju** [comment]
Hi, 
On a single machine, RCC is specifically blocking parallel runs. This is done because robots hitting issues trying to use the same files and other resources are just notoriously hard to find and resolve. These conflicts also more often than not affect each other which can pollute the data and potentially cause security issues.

For parallel executions, we recommend using separate runtime environments and orchestration ([more here](https://robocorp.com/docs/robocorp-cloud/robot-workforce). So you can for example use virtual machines to isolate the executions from each other.

Would be interested in hearing more of your use case on the "why" tough, but maybe a better venue for that would be our [forum](https://forum.robocorp.com)
