### ISSUE TITLE
Failed to create an environment due to ssl verification issues

### ISSUE THREAD

**Issue by Mino-dev** [robocorp/rcc#24]
**Describe the issue**
Failed to create environment after running the `rcc run` command.

**How to reproduce**

Following the https://github.com/robocorp/rcc#getting-started section of this repo:

1.) Create a standard robot from template `rcc robot initialize -t standard`
2.) Use `rcc run` command

**Log**
https://gist.github.com/Mino-dev/fbf48d7344ee2f9343b7caf63aa69b8c

**Versions**
- rcc v11.4.3
- python 3.9.7
- windows 10.0.18363

The system is currently running with zscaler client connector which causes issues not only in this tool but also in `conda`,  `mamba` and even `curl`. However, there are workarounds on those like disabling the ssl verification (last resort) or pointing it to another valid cert file via configuration files.  I do have a `.mambarc` and `.condarc` in my user home directory but it seems that it's being ignored. 

If there are current solutions for my issue please do let me know. And if you deemed that this is not an issue and/or inappropriate with RCC, please let me know so I can close this issue. 

Thanks in advance.

**Comment by kariharju** [comment]
Hi,
If think the only solution for this would be the `settings.yaml` in ROBOCORP_HOME folder.
You can generate this file with `rcc config settings` -command and there we have the setting to ignore SSL verifications:
```yaml
certificates:
  verify-ssl: true
```

In regards to `.mambarc` and basically all user-specific config files we are trying to isolate the robot executions so that the user-specific settings cannot affect those (and in the other direction so that robot executions don't mess up the user's system) so using those directly is a bit off the table in that sense.

So there is no other solution visible at the moment, but you did get us thinking.
