### ISSUE TITLE
rcc may have a problem with Chinese garbled code?

### ISSUE THREAD

**Issue by 893949088** [robocorp/rcc#35]
![image](https://user-images.githubusercontent.com/4034377/170808298-d48e5d0c-7038-4963-8b70-5c33d0dccb51.png)

**Comment by 893949088** [comment]
@kariharju

**Comment by vjmp** [comment]
@893949088 

Can you please provide following information (and not as screenshots, but as source files):

1. your `robot.yaml` file
2. your `conda.yaml` file
3. your `task.py` file

Or provide public github repository, where example can be cloned.

In addition, what are:

1. python version you are using when you run "python task.py" in screenshot
2. what is codepage that you are using in your windows

**Comment by vjmp** [comment]
Could you also run following script on your task.py file:
```
#!/bin/env python3

import sys

def dump(filename):
    with open(filename, encoding='utf-8') as source:
        for line in source:
            print(filename, line, end='')

if __name__ == '__main__':
    for filename in sys.argv[1:]:
        dump(filename)
```

**Comment by 893949088** [comment]
@vjmp 
github repository:  https://github.com/893949088/robocorp_test.git

env:
1. python : 3.7.5
2. rpaframework : 14.2.0
3. rcc : 11.9.10
4. codepage : vs code

github repository two example:
1. py_robot
![image](https://user-images.githubusercontent.com/4034377/171076915-150eb45a-500e-48b0-abd1-ca6eb151986f.png)

2. rpa_robot
![image](https://user-images.githubusercontent.com/4034377/171076795-d66a0871-75b1-40c1-a28b-6eb684c0ee25.png)

**Comment by vjmp** [comment]
@893949088 

Few notes.

- for codepage, see this: https://robocorp.com/docs/troubleshooting/windows-codepage
- both those bots produce correct output on my linux, so my current guess is that this is codepage issue
- since you have disabled `conda.yaml` in your `robot.yaml`, what are you expecting to get from using `rcc`?
- so, what is your use-case here?

So, please verify your real codepage, and then report back if that fixes the problem?
