### ISSUE TITLE
How to optimize pre-building of environments

### ISSUE THREAD

**Issue by aravindreddyravula** [robocorp/rcc#46]
I have a few questions

(1) Can I build an environment only for a specific operating system?
(2) The environment built is a large file(hololib.zip) of at least 100s of MB. How can I optimize it? Reduce the size of the environment so that I can port it easily

**Comment by vjmp** [comment]
First of all, for support questions like these, please consider using:

- community slack at https://robocorp-developers.slack.com/
- forum at https://forum.robocorp.com/
- or submit an issue via apps, see: https://robocorp.com/docs/troubleshooting/submit-issue

Why? Because those places have much more people looking than these GH issues. More people means faster responses and more ideas how to solve these kind of support questions.

**Comment by vjmp** [comment]
Now about those support questions:

1. Environment is currently build only for one specific OS, and that is OS that you run environment build commands. Currently there is no support for building environments for other OSes from some different OS.
2. For smaller environments there is no easy answer, but here is some ideas:

- learn to use just core libraries, not things that you are already familiar with (trade-off between size and convenience)
- include only those library dependencies that you need and nothing extra
- write simple things in your own code instead of bringing in huge libraries with lots of dependencies
- avoid using libraries that bring in lots of extra dependencies

And if you want to continue discussion on this topic, please join our community slack, and ask more details there.
