### ISSUE TITLE
Option to disable DNS lookup in diagnostics

### ISSUE THREAD

**Issue by fabolhak** [robocorp/rcc#48]
Hello, 
thank you for your great tool. It really helps us to create and maintain our test environments. Unfortunately, our team sits behind a company proxy. Downloading and setting up the rcc environment works fine (http traffic via company proxy is allowed). However, we get DNS lookup errors when running the diagnostic command or when opening visual studio code with the `Robocorp Code` extension installed. Bare DNS lookups are not allowed to pass our company proxy / firewall. 
I was wondering if there is any way to disable the DNS lookup checks since the rest works fine (via http)? It seems that the check is being done on a list of dns names: https://github.com/robocorp/rcc/blob/master/operations/diagnostics.go#L138. I already tried removing all preconfigured DNS entries in my settings and profile yaml file. However, rcc still tries to lookup some (default?) hostnames.

Thank you and kindest regards,
Fabian

**Comment by vjmp** [comment]
Thank you for your interest, @fabolhak .

From rcc point of view, all those diagnostics are just information, that users are free to ignore. For now, they are there just to inform, that there might be problems down the road. And if users (like your self) know better, then they can just ignore them, because they know that it is not actual problem in their case.

And it is little bit unclear, how our tooling can work when DNS resolution is not allowed, since lots of our functionality needs that (conversion from names to actual IP addresses to use).

So for now, we are not planning to put flags or options in front of diagnostics, in rcc. For other tools (like VS Code), diagnostics output already has "category", which tooling can use to partially ignore those warnings.

We might revisit this functionality later, but currently there is no timeline for it. If you think this is urgent, and needs different decision, please provide additional information for us to understand why current functionality is not enough for you.

If no additional information is provided, this issue will soon be closed.

**Comment by vjmp** [comment]
Closing since no additional information provided.

**Comment by fabolhak** [comment]
Thats fine for me. Thank you for the answer and explanation :)
