### ISSUE TITLE
RCC network diagnostic should also check registry.npmjs.org

### ISSUE THREAD

**Issue by simonmeggle** [robocorp/rcc#56]
I am behind a corporate proxy where the domains accessed by RCC have to be allowed selectively.
Installing Browserlibrary / Playwright fails even with all the domains listed in `rcc config diag` because registry.npmjs.org is not accessible. 

![image](https://github.com/robocorp/rcc/assets/1897410/f1370a54-3c9d-4e39-a0e4-7fa5599555db)

**Comment by vjmp** [comment]
Will not be adding this to rcc for now, since for Setup Utility (enterprise) users this will be breaking change (additional warning that will suddenly come up). And that would mean that this is Major version update for rcc. And even now, there is better ways around this, which we are already using with our stack/tooling.

Those alternative ways are:
- private/customized `settings.yaml` file where section `diagnostics-hosts:` section (legacy option, below better ones)
- use profiles to embed that `settings.yaml` configuration, and use Setup Utility to build those (better, but ...)
- use `rcc configuration netdiagnostics --check customized-checks.yaml` and create that `customized-check.yaml` either once "globally" or "case by case" (this is tooling build specially for these cases, where custom addresses and URLs are needed, like enterprises; we use this internally)

Note that currently supported "platform" for rcc are:
- robocorp.com
- pypi.org
- conda.anaconda.org
- github.com (to some extent)

If/when we add proper "nodejs" support, then that is different thing.

Will close this issue shortly, since currently there are already ways do this.

**Comment by simonmeggle** [comment]
Ok, thanks @vjmp ! Ok for me!
