### ISSUE TITLE
Make holotree statistics output machine readable (--json)

### ISSUE THREAD

**Issue by simonmeggle** [robocorp/rcc#58]
The build and runtime statistics of `rcc holotree stats`  give a worthful insight.   :+1: 

Is there any possibility to give `rcc holotree stats` an option `--json`, as it is already available for `rcc diag`  ? 
This would make the data machine readable. => this could be read by monitoring systems which observe any performance declinement and collect the data for historical graphs. 

Thanks a lot - best regards,
Simon

**Comment by vjmp** [comment]
This was originally **NOT** done, because that data is not uniform, and units on different sections are different (percents, seconds, counts). And they are also not locked down and cannot promise that they will remain comparable from version to another.

Can you open up your use-case, and identify which details are important to that use-case. Also do you want values as text (like: "89.5%") or numbers (like: 0.895). Numerical accuracy might also be challenging, since currently those values are rounded values, not exactly absolutely accurate.

Also note, that lots of these are machine specific, so they should not be compared between systems and performance will differ from machine to machine.

**Comment by simonmeggle** [comment]
Thanks for your questions. 👍  I will clarify this with one of the Checkmk developers who can give a qualified answer about the best formats which could be provided here. If you want, you can close this issue meanwhile; I will answer here as soon as we can go on.
