### ISSUE TITLE
Unable to run after importing pre built environment

### ISSUE THREAD

**Issue by helang0616** [robocorp/rcc#60]
I exported the pre built environment using the 'rcc holotree export' command and gave hololib.zip to another computer. However, the other computer was unable to run the robot after importing, resulting in a lock acquisition failure prompt. The lock file directory is the directory of my exported environment computer (including the user directory), and the second computer does not have a corresponding directory,

**Comment by vjmp** [comment]
1. Have you enabled shared holotree on both machines, and on both users accounts that are part of this export/import process?
2. Are both machines running same operating system, and versions? What is this operating system and its version?
3. What are concreate error messages and stack traces that you are seeing?
4. About locks, are these rcc created locks, or locks that your automation is using/creating? Can you be more specific on paths that are involved with these locks, otherwise it is very unclear which locks we are talking about?
5. Note, that rcc wont create arbitrary directory structure from from original machine to new target machine, only holotree related directory structure. If you automation needs some special, outside of holotree directories, it is responsibility of your automation to create those directory structures.

So, in general, more information is needed to help you resolve this. Also, if this is using our tooling, like Setup Utility, Worker, or VS Code plugins, please consider submitting issue report directly from those, so that we get logs that reveal actual problem in log files produced by tooling. Thank you.

**Comment by vjmp** [comment]
@helang0616, please provide additional information, or close this issue. Thank you.

**Comment by vjmp** [comment]
Closing this issue, since no new information was provided and this seems not to be software issue with rcc.
